"""empty message

Revision ID: 324d297991e7
Revises: 
Create Date: 2020-10-30 17:02:45.507733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324d297991e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_user_signal',
    sa.Column('registered_user_signal_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('registered_user_signal_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('recovery_code_hash', sa.String(length=128), nullable=True),
    sa.Column('two_factor_login', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_update_signal',
    sa.Column('user_update_signal_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_update_signal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_update_signal')
    op.drop_table('user')
    op.drop_table('registered_user_signal')
    # ### end Alembic commands ###
