"""empty message

Revision ID: 655213bc148f
Revises: 
Create Date: 2020-10-31 16:44:14.611972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655213bc148f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_user_signal',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('registered_user_signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'registered_user_signal_id')
    )
    op.create_table('user_registration',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('recovery_code_hash', sa.String(length=128), nullable=True),
    sa.Column('two_factor_login', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_update_signal',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_update_signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'user_update_signal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_update_signal')
    op.drop_table('user_registration')
    op.drop_table('registered_user_signal')
    # ### end Alembic commands ###
