"""empty message

Revision ID: 8f82547123fc
Revises: 9f766201fe3a
Create Date: 2025-05-04 12:51:50.305959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f82547123fc'
down_revision = '9f766201fe3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activate_user_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_from_ip', postgresql.INET(), nullable=True))
        batch_op.add_column(sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), nullable=False))

    with op.batch_alter_table('deleted_registration_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), nullable=False))

    with op.batch_alter_table('user_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_from_ip', postgresql.INET(), nullable=True))
        batch_op.add_column(sa.Column('registered_at', sa.TIMESTAMP(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_registration', schema=None) as batch_op:
        batch_op.drop_column('registered_at')
        batch_op.drop_column('registered_from_ip')

    with op.batch_alter_table('deleted_registration_signal', schema=None) as batch_op:
        batch_op.drop_column('inserted_at')

    with op.batch_alter_table('activate_user_signal', schema=None) as batch_op:
        batch_op.drop_column('inserted_at')
        batch_op.drop_column('registered_from_ip')

    # ### end Alembic commands ###
