"""empty message

Revision ID: 9f766201fe3a
Revises: 24db47bcaf08
Create Date: 2025-05-03 21:05:13.999095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f766201fe3a'
down_revision = '24db47bcaf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_registration_signal',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_registration_signal')
    # ### end Alembic commands ###
