"""empty message

Revision ID: d4bf9e85b7c3
Revises: a5da48a60001
Create Date: 2025-04-27 22:14:12.656482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bf9e85b7c3'
down_revision = 'a5da48a60001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_update_signal')
    with op.batch_alter_table('user_registration', schema=None) as batch_op:
        batch_op.alter_column('recovery_code_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('two_factor_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_login', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('recovery_code_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    op.create_table('user_update_signal',
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_update_signal_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'user_update_signal_id', name='user_update_signal_pkey')
    )
    # ### end Alembic commands ###
