"""empty message

Revision ID: e61c239caaae
Revises: 376fc80bbed6
Create Date: 2025-05-07 19:50:46.482789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61c239caaae'
down_revision = '376fc80bbed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=False, comment='Only registrations with status=0 are allowed to log in.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_registration', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
